# This compose file overrides the default compose file for production

services:
  redis:
    restart: "no"
    ports:
      - "6379:6379"

  redisinsight:
    restart: "no"
    ports:
      - "5540:5540"

  qdrant:
    ports:
      - "6333:6333" # REST API

  adminer:
    ports:
      - "8555:8080"

  api:
    ports:
      - "8444:8444"
