# Base compose file

services:
  db:
    image: postgres:17.5-bookworm
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - seas-db-data:/var/lib/postgresql/pgdata
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/pgdata
      - POSTGRES_DB=${POSTGRES_DB?Variable not set}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD?Variable not set}
      - POSTGRES_USER=${POSTGRES_USER?Variable not set}
    networks:
      - seas

  redis:
    image: redis:8.2-bookworm
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - redis-data:/data
    command: redis-server --protected-mode no --requirepass "$REDIS_PASSWORD" --bind "0.0.0.0"
    env_file: 
      - .env
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD?Variable not set}
    networks:
      - seas

  redisinsight:
    image: redislabs/redisinsight:2.70
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "curl", "-f", "http://localhost:5540/health" ]
      interval: 30s
      timeout: 5s
      retries: 3
    volumes:
      - redisinsight-data:/data
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - seas

  qdrant:
    image: qdrant/qdrant:latest
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "bash -c ':> /dev/tcp/127.0.0.1/6333' || exit 1" ]
      timeout: 5s
      retries: 3
    volumes:
      - seas-qdrant-data:/qdrant/storage
    environment:
      - QDRANT__SERVICE__API_KEY=${QDRANT_API_KEY?Variable not set}
    networks:
      - seas

  adminer:
    image: adminer:5.3.0
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      - ADMINER_DESIGN=rmsoft
    networks:
      - seas

  api:
    image: "${API_IMAGE}:${API_TAG-latest}"
    restart: always
    env_file:
      - .env
    environment:
      - API_PORT=8444
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=${POSTGRES_DB?Variable not set}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD?Variable not set}
      - POSTGRES_USER=${POSTGRES_USER?Variable not set}
      - FIRST_USER_PASSWORD=${FIRST_USER_PASSWORD?Variable not set}
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
      - ENVIRONMENT=${ENVIRONMENT:-production}
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8444/health" ]
      interval: 10s
      timeout: 5s
      retries: 3
    depends_on:
      db:
        condition: service_healthy
      qdrant:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - seas

volumes:
  seas-db-data:
  seas-qdrant-data:
  redis-data:
  redisinsight-data:

networks:
  seas:
