services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.cuda
    restart: always
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
