// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { AuthLoginForAccessTokenData, AuthLoginForAccessTokenResponse, AuthLoginViaGoogleOauth2Response, AuthSignupData, AuthSignupResponse, AuthTestTokenResponse, AuthSignoutResponse, AuthRecoverPasswordData, AuthRecoverPasswordResponse, AuthResetPasswordData, AuthResetPasswordResponse, AuthRecoverPasswordHtmlContentData, AuthRecoverPasswordHtmlContentResponse, ChatsGetChatSessionsResponse, ChatsCreateChatSessionData, ChatsCreateChatSessionResponse, ChatsGetChatSessionData, ChatsGetChatSessionResponse, ChatsUpdateChatSessionData, ChatsUpdateChatSessionResponse, ChatsGetChatMessagesData, ChatsGetChatMessagesResponse, ChatsCreateNewMessageData, ChatsCreateNewMessageResponse, UsersGetUsersData, UsersGetUsersResponse, UsersCreateUserData, UsersCreateUserResponse, UsersGetUserMeResponse, UsersDeleteUserMeResponse, UsersUpdateUserMeData, UsersUpdateUserMeResponse, UsersUpdateMyPasswordData, UsersUpdateMyPasswordResponse, UsersGetUserByIdData, UsersGetUserByIdResponse, UsersUpdateUserByIdData, UsersUpdateUserByIdResponse, UsersDeleteUserByIdData, UsersDeleteUserByIdResponse, UtilsHealthCheckResponse, UtilsHtmlResponse, UtilsTestSendEmailData, UtilsTestSendEmailResponse, UtilsTestSendEmailBackgroundData, UtilsTestSendEmailBackgroundResponse } from './types.gen';

export class AuthService {
    /**
     * Login For Access Token
     * Login with username and password to get an access token for future requests.
     * @param data The data for the request.
     * @param data.formData
     * @returns LoginResponse Successful Response
     * @throws ApiError
     */
    public static loginForAccessToken(data: AuthLoginForAccessTokenData): CancelablePromise<AuthLoginForAccessTokenResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/auth/login/access-token',
            formData: data.formData,
            mediaType: 'application/x-www-form-urlencoded',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Login Via Google Oauth2
     * Login with Google OAuth2.
     * @returns unknown Successful Response
     * @throws ApiError
     */
    public static loginViaGoogleOauth2(): CancelablePromise<AuthLoginViaGoogleOauth2Response> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/auth/login/google-oauth2'
        });
    }
    
    /**
     * Google Oauth2 Callback
     * Callback to handle redirect from Google OAuth2.
     * @throws ApiError
     */
    public static googleOauth2Callback(): CancelablePromise<void> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/auth/login/google-oauth2/callback',
            errors: {
                307: 'Successful Response'
            }
        });
    }
    
    /**
     * Signup
     * Sign up a new user.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static signup(data: AuthSignupData): CancelablePromise<AuthSignupResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/auth/signup',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Test Token
     * Test if your access token is valid.
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static testToken(): CancelablePromise<AuthTestTokenResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/auth/login/test-token'
        });
    }
    
    /**
     * Signout
     * Signout the user
     * @returns MessageResponse Successful Response
     * @throws ApiError
     */
    public static signout(): CancelablePromise<AuthSignoutResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/auth/signout'
        });
    }
    
    /**
     * Recover Password
     * Recover password by email.
     * @param data The data for the request.
     * @param data.email
     * @returns MessageResponse Successful Response
     * @throws ApiError
     */
    public static recoverPassword(data: AuthRecoverPasswordData): CancelablePromise<AuthRecoverPasswordResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/auth/password-recovery/{email}',
            path: {
                email: data.email
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Reset Password
     * Reset password
     * @param data The data for the request.
     * @param data.requestBody
     * @returns MessageResponse Successful Response
     * @throws ApiError
     */
    public static resetPassword(data: AuthResetPasswordData): CancelablePromise<AuthResetPasswordResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/auth/password-reset',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Recover Password Html Content
     * Recover password with HTML. Requires superuser permissions.
     * @param data The data for the request.
     * @param data.email
     * @returns string Successful Response
     * @throws ApiError
     */
    public static recoverPasswordHtmlContent(data: AuthRecoverPasswordHtmlContentData): CancelablePromise<AuthRecoverPasswordHtmlContentResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/auth/password-recovery-html-content/{email}',
            path: {
                email: data.email
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
}

export class ChatsService {
    /**
     * Get Chat Sessions
     * Get all chat sessions for the current user.
     * @returns ChatSessionPublic Successful Response
     * @throws ApiError
     */
    public static getChatSessions(): CancelablePromise<ChatsGetChatSessionsResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/chats/chat_sessions'
        });
    }
    
    /**
     * Create Chat Session
     * Create a new chat session for the current user.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns ChatSessionPublic Successful Response
     * @throws ApiError
     */
    public static createChatSession(data: ChatsCreateChatSessionData): CancelablePromise<ChatsCreateChatSessionResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/chats/chat_sessions',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Get Chat Session
     * Get a specific chat session by ID for the current user.
     * @param data The data for the request.
     * @param data.chatSessionId
     * @returns ChatSessionPublic Successful Response
     * @throws ApiError
     */
    public static getChatSession(data: ChatsGetChatSessionData): CancelablePromise<ChatsGetChatSessionResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/chats/chat_sessions/{chat_session_id}',
            path: {
                chat_session_id: data.chatSessionId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update Chat Session
     * Update a chat session by ID.
     * @param data The data for the request.
     * @param data.chatSessionId
     * @param data.requestBody
     * @returns ChatSessionPublic Successful Response
     * @throws ApiError
     */
    public static updateChatSession(data: ChatsUpdateChatSessionData): CancelablePromise<ChatsUpdateChatSessionResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/chats/chat_sessions/{chat_session_id}',
            path: {
                chat_session_id: data.chatSessionId
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Get Chat Messages
     * Get chat messages for a specific session.
     * @param data The data for the request.
     * @param data.chatSessionId
     * @returns unknown Successful Response
     * @throws ApiError
     */
    public static getChatMessages(data: ChatsGetChatMessagesData): CancelablePromise<ChatsGetChatMessagesResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/chats/chat_sessions/{chat_session_id}/messages',
            path: {
                chat_session_id: data.chatSessionId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Create New Message
     * Create a new message in a chat session.
     * @param data The data for the request.
     * @param data.chatSessionId
     * @param data.requestBody
     * @returns ChatMessagePublic Successful Response
     * @throws ApiError
     */
    public static createNewMessage(data: ChatsCreateNewMessageData): CancelablePromise<ChatsCreateNewMessageResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/chats/chat_sessions/{chat_session_id}/messages',
            path: {
                chat_session_id: data.chatSessionId
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
}

export class UsersService {
    /**
     * Get Users
     * Get users. Requires superuser permissions.
     * @param data The data for the request.
     * @param data.offset
     * @param data.limit
     * @returns UserPublicList Successful Response
     * @throws ApiError
     */
    public static getUsers(data: UsersGetUsersData = {}): CancelablePromise<UsersGetUsersResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/',
            query: {
                offset: data.offset,
                limit: data.limit
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Create User
     * Create a new user. Requires superuser permissions.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static createUser(data: UsersCreateUserData): CancelablePromise<UsersCreateUserResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/users/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Get User Me
     * Get current user
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static getUserMe(): CancelablePromise<UsersGetUserMeResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/me'
        });
    }
    
    /**
     * Delete User Me
     * Delete current user
     * @returns MessageResponse Successful Response
     * @throws ApiError
     */
    public static deleteUserMe(): CancelablePromise<UsersDeleteUserMeResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/users/me'
        });
    }
    
    /**
     * Update User Me
     * Update current user's information
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static updateUserMe(data: UsersUpdateUserMeData): CancelablePromise<UsersUpdateUserMeResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/users/me',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update My Password
     * Update current user's password
     * @param data The data for the request.
     * @param data.requestBody
     * @returns MessageResponse Successful Response
     * @throws ApiError
     */
    public static updateMyPassword(data: UsersUpdateMyPasswordData): CancelablePromise<UsersUpdateMyPasswordResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/users/me/password',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Get User By Id
     * Get user by ID
     * @param data The data for the request.
     * @param data.userId
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static getUserById(data: UsersGetUserByIdData): CancelablePromise<UsersGetUserByIdResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/{user_id}',
            path: {
                user_id: data.userId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update User By Id
     * Update a user by ID. Requires superuser permissions.
     * @param data The data for the request.
     * @param data.userId
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static updateUserById(data: UsersUpdateUserByIdData): CancelablePromise<UsersUpdateUserByIdResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/users/{user_id}',
            path: {
                user_id: data.userId
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Delete User By Id
     * Delete a user by ID. Requires superuser permissions.
     * @param data The data for the request.
     * @param data.userId
     * @returns MessageResponse Successful Response
     * @throws ApiError
     */
    public static deleteUserById(data: UsersDeleteUserByIdData): CancelablePromise<UsersDeleteUserByIdResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/users/{user_id}',
            path: {
                user_id: data.userId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
}

export class UtilsService {
    /**
     * Health Check
     * @returns unknown Successful Response
     * @throws ApiError
     */
    public static healthCheck(): CancelablePromise<UtilsHealthCheckResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/health'
        });
    }
    
    /**
     * Html
     * @returns string Successful Response
     * @throws ApiError
     */
    public static html(): CancelablePromise<UtilsHtmlResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/html'
        });
    }
    
    /**
     * Test Send Email
     * Test sending email
     * @param data The data for the request.
     * @param data.emailTo
     * @returns MessageResponse Successful Response
     * @throws ApiError
     */
    public static testSendEmail(data: UtilsTestSendEmailData): CancelablePromise<UtilsTestSendEmailResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/test-send-email',
            query: {
                email_to: data.emailTo
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Test Send Email Background
     * Test sending email using FastAPI background tasks
     * @param data The data for the request.
     * @param data.emailTo
     * @returns MessageResponse Successful Response
     * @throws ApiError
     */
    public static testSendEmailBackground(data: UtilsTestSendEmailBackgroundData): CancelablePromise<UtilsTestSendEmailBackgroundResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/test-send-email-background',
            query: {
                email_to: data.emailTo
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
}