// This file is auto-generated by @hey-api/openapi-ts

export type Body_auth_login = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type ChatMessageCreate = {
    sender: Sender;
    content: string;
};

export type ChatMessagePublic = {
    id: string;
    chat_session_id: string;
    sender: Sender;
    content: string;
    created_at: string;
};

export type ChatSessionCreate = {
    session_metadata?: {
        [key: string]: unknown;
    };
};

export type ChatSessionPublic = {
    id: string;
    is_favorite: boolean;
    user_id: string;
    created_at: string;
    updated_at: string;
    session_metadata: {
        [key: string]: unknown;
    };
};

export type ChatSessionUpdate = {
    is_favorite?: (boolean | null);
    session_metadata?: ({
    [key: string]: unknown;
} | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type LoginResponse = {
    message: string;
    token_type?: string;
    expires_in: number;
};

export type MessageResponse = {
    status?: MessageStatus;
    message: string;
};

export type MessageStatus = 'SUCCESS' | 'ERROR';

export type NewPassword = {
    token: string;
    new_password: string;
};

export type OAuthProvider = 'GOOGLE' | 'GITHUB' | 'LOCAL';

export type Sender = 'USER' | 'BOT' | 'SYSTEM';

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    username: string;
    email: string;
    full_name: string;
    is_active?: boolean;
    password: string;
    role?: UserRole;
    oauth_provider?: OAuthProvider;
};

export type UserPublic = {
    id: string;
    username: string;
    email: string;
    full_name: string;
    is_active: boolean;
    role: UserRole;
    oauth_provider: OAuthProvider;
    created_at: string;
};

export type UserPublicList = {
    users: Array<UserPublic>;
    count: number;
};

export type UserRegister = {
    username: string;
    email: string;
    full_name: string;
    password: string;
};

export type UserRole = 'ADMIN' | 'USER';

export type UserUpdate = {
    email?: (string | null);
    full_name?: (string | null);
    is_active?: (boolean | null);
    role?: (UserRole | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    email?: (string | null);
    full_name?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type AuthLoginData = {
    formData: Body_auth_login;
};

export type AuthLoginResponse = (LoginResponse);

export type AuthLoginViaGoogleOauth2Data = {
    responseClass?: unknown;
};

export type AuthLoginViaGithubOauth2Data = {
    responseClass?: unknown;
};

export type AuthSignupData = {
    requestBody: UserRegister;
};

export type AuthSignupResponse = (UserPublic);

export type AuthTestTokenResponse = (UserPublic);

export type AuthSignoutResponse = (MessageResponse);

export type AuthRecoverPasswordData = {
    email: string;
};

export type AuthRecoverPasswordResponse = (MessageResponse);

export type AuthResetPasswordData = {
    requestBody: NewPassword;
};

export type AuthResetPasswordResponse = (MessageResponse);

export type AuthRecoverPasswordHtmlContentData = {
    email: string;
};

export type AuthRecoverPasswordHtmlContentResponse = (string);

export type ChatsGetChatSessionsResponse = (Array<ChatSessionPublic>);

export type ChatsCreateChatSessionData = {
    requestBody: ChatSessionCreate;
};

export type ChatsCreateChatSessionResponse = (ChatSessionPublic);

export type ChatsGetChatSessionData = {
    chatSessionId: string;
};

export type ChatsGetChatSessionResponse = (ChatSessionPublic);

export type ChatsUpdateChatSessionData = {
    chatSessionId: string;
    requestBody: ChatSessionUpdate;
};

export type ChatsUpdateChatSessionResponse = (ChatSessionPublic);

export type ChatsGetChatMessagesData = {
    chatSessionId: string;
};

export type ChatsGetChatMessagesResponse = (unknown);

export type ChatsCreateNewMessageData = {
    chatSessionId: string;
    requestBody: ChatMessageCreate;
};

export type ChatsCreateNewMessageResponse = (ChatMessagePublic);

export type UsersGetUsersData = {
    limit?: number;
    offset?: number;
};

export type UsersGetUsersResponse = (UserPublicList);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersGetUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (MessageResponse);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdateMyPasswordData = {
    requestBody: UpdatePassword;
};

export type UsersUpdateMyPasswordResponse = (MessageResponse);

export type UsersGetUserByIdData = {
    userId: string;
};

export type UsersGetUserByIdResponse = (UserPublic);

export type UsersUpdateUserByIdData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserByIdResponse = (UserPublic);

export type UsersDeleteUserByIdData = {
    userId: string;
};

export type UsersDeleteUserByIdResponse = (MessageResponse);

export type UtilsHealthCheckResponse = (unknown);

export type UtilsHtmlResponse = (string);

export type UtilsTestSendEmailData = {
    emailTo: string;
};

export type UtilsTestSendEmailResponse = (MessageResponse);

export type UtilsTestSendEmailBackgroundData = {
    emailTo: string;
};

export type UtilsTestSendEmailBackgroundResponse = (MessageResponse);