// This file is auto-generated by @hey-api/openapi-ts

export type Body_auth_login = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type Body_rag_add_document_to_database = {
    /**
     * The document to add to the database
     */
    file: (Blob | File);
};

export type Body_rag_add_document_to_database_in_batch = {
    /**
     * The documents to add to the database
     */
    files: Array<((Blob | File))>;
};

export type Body_rag_query_expansion = {
    /**
     * The query to expand
     */
    query: string;
    /**
     * Number of new queries to expand the query. Less than 1 means no expansion.
     */
    num_new_queries?: number;
};

export type Body_rag_split_markdown_on_headers = {
    /**
     * The document to split on headers
     */
    file: (Blob | File);
};

export type ChatMessageCreate = {
    sender: Sender;
    content: string;
};

export type ChatMessagePublic = {
    id: string;
    chat_session_id: string;
    sender: Sender;
    content: string;
    created_at: string;
};

export type ChatSessionCreate = {
    session_metadata?: {
        [key: string]: unknown;
    };
};

export type ChatSessionPublic = {
    id: string;
    is_favorite: boolean;
    user_id: string;
    created_at: string;
    updated_at: string;
    session_metadata: {
        [key: string]: unknown;
    };
};

export type ChatSessionUpdate = {
    is_favorite?: (boolean | null);
    session_metadata?: ({
    [key: string]: unknown;
} | null);
};

/**
 * Type of internal tags, build from payload Distance function types used to compare vectors
 */
export type Distance = 'Cosine' | 'Euclid' | 'Dot' | 'Manhattan';

export type DocumentSectionChunkPublic = {
    id: string;
    content: string;
    chunk_index: number;
    chunk_metadata: {
        [key: string]: unknown;
    };
    similarity_score?: (number | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type LoginResponse = {
    message: string;
    token_type?: string;
    expires_in: number;
};

export type MessageResponse = {
    status?: MessageStatus;
    message: string;
    extra?: {
        [key: string]: unknown;
    };
};

export type MessageStatus = 'SUCCESS' | 'ERROR';

export type NewPassword = {
    token: string;
    new_password: string;
};

export type OAuthProvider = 'GOOGLE' | 'GITHUB' | 'LOCAL';

export type QueryParams = {
    /**
     * The user's chat query
     */
    query: string;
    /**
     * Number of chunks to retrieve
     */
    limit?: number;
    /**
     * Threshold for similarity search
     */
    threshold?: number;
    /**
     * Number of new queries to expand the query. Less than 1 means no expansion.
     */
    num_new_queries?: number;
    /**
     * Whether to rerank the retrieved chunks
     */
    rerank?: boolean;
    /**
     * The ID of the chat session. If provided, the query and response will be added to the chat session as new messages.
     */
    chat_session_id?: (string | null);
};

export type RecomputeEmbeddingsParams = {
    /**
     * The name of the Qdrant database to compute embeddings for
     */
    qdrant_db_name: string;
    /**
     * The size of the embeddings to compute
     */
    embeddings_size: number;
    /**
     * The distance function to use for the embeddings
     */
    distance_function: Distance;
};

export type Sender = 'USER' | 'BOT' | 'SYSTEM';

export type SimilaritySearchResult = {
    num_chunks: number;
    reranked: boolean;
    query: string;
    expanded_queries?: (Array<(string)> | null);
    chunks: Array<DocumentSectionChunkPublic>;
    /**
     * Time taken to expand the query using LLM
     */
    query_expansion_time?: (number | null);
    /**
     * Time taken to embed the query using LLM
     */
    embedding_time?: (number | null);
    /**
     * Time taken to search for similar chunks in the database
     */
    similarity_search_time?: (number | null);
    /**
     * Time taken to retrieve the chunks from the database
     */
    chunk_retrieval_time?: (number | null);
    /**
     * Time taken to rerank the chunks
     */
    rerank_time?: (number | null);
    /**
     * Total time taken to process the query
     */
    total_sim_search_time: number;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    username: string;
    email: string;
    full_name: string;
    is_active?: boolean;
    password: string;
    role?: UserRole;
    oauth_provider?: OAuthProvider;
};

export type UserPublic = {
    id: string;
    username: string;
    email: string;
    full_name: string;
    is_active: boolean;
    role: UserRole;
    oauth_provider: OAuthProvider;
    created_at: string;
};

export type UserPublicList = {
    users: Array<UserPublic>;
    count: number;
};

export type UserRegister = {
    username: string;
    email: string;
    full_name: string;
    password: string;
};

export type UserRole = 'ADMIN' | 'USER';

export type UserUpdate = {
    email?: (string | null);
    full_name?: (string | null);
    is_active?: (boolean | null);
    role?: (UserRole | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    email?: (string | null);
    full_name?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type AuthLoginData = {
    formData: Body_auth_login;
};

export type AuthLoginResponse = (LoginResponse);

export type AuthLoginViaGoogleOauth2Data = {
    responseClass?: unknown;
};

export type AuthLoginViaGithubOauth2Data = {
    responseClass?: unknown;
};

export type AuthSignupData = {
    requestBody: UserRegister;
};

export type AuthSignupResponse = (UserPublic);

export type AuthTestTokenResponse = (UserPublic);

export type AuthSignoutResponse = (MessageResponse);

export type AuthRecoverPasswordData = {
    email: string;
};

export type AuthRecoverPasswordResponse = (MessageResponse);

export type AuthResetPasswordData = {
    requestBody: NewPassword;
};

export type AuthResetPasswordResponse = (MessageResponse);

export type AuthRecoverPasswordHtmlContentData = {
    email: string;
};

export type AuthRecoverPasswordHtmlContentResponse = (string);

export type ChatbotQueryData = {
    requestBody: QueryParams;
};

export type ChatbotQueryResponse = (unknown);

export type ChatbotQueryEvalData = {
    requestBody: QueryParams;
};

export type ChatbotQueryEvalResponse = (unknown);

export type ChatsGetChatSessionsResponse = (Array<ChatSessionPublic>);

export type ChatsCreateChatSessionData = {
    requestBody: ChatSessionCreate;
};

export type ChatsCreateChatSessionResponse = (ChatSessionPublic);

export type ChatsGetLatestChatSessionResponse = (ChatSessionPublic);

export type ChatsGetChatSessionData = {
    chatSessionId: string;
};

export type ChatsGetChatSessionResponse = (ChatSessionPublic);

export type ChatsUpdateChatSessionData = {
    chatSessionId: string;
    requestBody: ChatSessionUpdate;
};

export type ChatsUpdateChatSessionResponse = (ChatSessionPublic);

export type ChatsDeleteChatSessionData = {
    chatSessionId: string;
};

export type ChatsDeleteChatSessionResponse = (MessageResponse);

export type ChatsGetChatMessagesData = {
    chatSessionId: string;
};

export type ChatsGetChatMessagesResponse = (unknown);

export type ChatsCreateNewMessageData = {
    chatSessionId: string;
    requestBody: ChatMessageCreate;
};

export type ChatsCreateNewMessageResponse = (ChatMessagePublic);

export type RagAddDocumentToDatabaseData = {
    formData: Body_rag_add_document_to_database;
};

export type RagAddDocumentToDatabaseResponse = (MessageResponse);

export type RagAddDocumentToDatabaseInBatchData = {
    formData: Body_rag_add_document_to_database_in_batch;
};

export type RagAddDocumentToDatabaseInBatchResponse = (MessageResponse);

export type RagSimilaritySearchData = {
    requestBody: QueryParams;
};

export type RagSimilaritySearchResponse = (SimilaritySearchResult);

export type RagSplitMarkdownOnHeadersData = {
    formData: Body_rag_split_markdown_on_headers;
};

export type RagSplitMarkdownOnHeadersResponse = (unknown);

export type RagQueryExpansionData = {
    requestBody: Body_rag_query_expansion;
};

export type RagQueryExpansionResponse = (unknown);

export type RagExportDocumentSectionsChunksResponse = (unknown);

export type RagGetRagModelsStatusResponse = (unknown);

export type RagRecomputeEmbeddingsData = {
    requestBody: RecomputeEmbeddingsParams;
};

export type RagRecomputeEmbeddingsResponse = (unknown);

export type UsersGetUsersData = {
    limit?: number;
    offset?: number;
};

export type UsersGetUsersResponse = (UserPublicList);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersGetUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (MessageResponse);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdateMyPasswordData = {
    requestBody: UpdatePassword;
};

export type UsersUpdateMyPasswordResponse = (MessageResponse);

export type UsersGetUserByIdData = {
    userId: string;
};

export type UsersGetUserByIdResponse = (UserPublic);

export type UsersUpdateUserByIdData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserByIdResponse = (UserPublic);

export type UsersDeleteUserByIdData = {
    userId: string;
};

export type UsersDeleteUserByIdResponse = (MessageResponse);

export type UtilsHealthCheckResponse = (unknown);

export type UtilsTestSendEmailData = {
    emailTo: string;
};

export type UtilsTestSendEmailResponse = (MessageResponse);

export type UtilsTestSendEmailBackgroundData = {
    emailTo: string;
};

export type UtilsTestSendEmailBackgroundResponse = (MessageResponse);