[project]
name = "seas-api"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.12"
authors = [
    { name = "Minh-Thien Nguyen", email = "minhnguyent546@gmail.com" }
]
dependencies = [
    "alembic>=1.16.2",
    "asyncpg>=0.30.0",
    "fastapi[standard]>=0.115.14,<0.116.0",
    "loguru>=0.7.3",
    "passlib>=1.7.4",
    "bcrypt==4.0.1",
    "psycopg2>=2.9.10",
    "pydantic>=2.11.7,<2.12.0",
    "pydantic-settings>=2.10.1,<2.11.0",
    "pyjwt>=2.10.1",
    "python-dotenv>=1.1.0,<2.0.0",
    "pytz>=2025.2",
    "sqlmodel>=0.0.24",
    "httpx>=0.28.1",
    "psutil>=7.0.0",
    "emails>=0.6",
    "authlib>=1.6.0",
    "starlette[full]>=0.46.2",
    "langchain>=0.3.26",
    "langchain-google-genai>=2.1.8",
    "sqlalchemy-utils>=0.41.2",
    "langchain-community>=0.3.27",
    "langchain-qdrant>=0.2.0",
    "python-frontmatter>=1.1.0",
    "qdrant-client>=1.13.1",
    "markdown-to-data>=1.0.0",
    "langchain-openai>=0.3.28",
    "jinja2>=3.1.6",
    "firecrawl>=2.16.1",
    "pillow>=11.3.0",
    "langgraph>=0.5.4",
    "tavily-python>=0.7.10",
    "langchain-tavily>=0.2.11",
    "graphviz>=0.21",
]

[dependency-groups]
dev = [
    "autoflake>=2.3.1,<3.0.0",
    "colorama>=0.4.6",
    "firecrawl>=2.16.1",
    "flake8>=7.2.0,<8.0.0",
    "isort>=6.0.1,<7.0.0",
    "pytest>=8.4.1",
    "pytest-asyncio>=1.0.0",
    "pytest-cov>=6.2.1",
    "ruff>=0.12.1",
    "tabulate>=0.9.0",
]

[tool.ruff]
line-length = 79
target-version = "py312"

[tool.ruff.lint]
select = [
    "B",      # flake8-bugbear
    "C",      # comple-structure
    "E",      # pycodestyle errors
    "F",      # pyflakes
    "I",      # isort
    "W",      # pycodestyle warnings
    "RUF013", # implicit-optional
    "UP006",  # non-pep585-annotation (e.g. `list[int]` instead of `List[int]`)
]
extend-safe-fixes = ["UP006"]
ignore = [
    "C901", # complex-structure
    "E101", # mixed-spaces-and-tabs
    "E501", # line-too-long
    "E741", # ambiguous-variable-name
    "F402", # import-shadowed-by-loop-var
    "F823", # undefined-local
]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = [
    "E402", # module-import-not-at-top-of-file
    "F401", # unused-import
    "F403", # undefined-local-with-import-star
]

[tool.ruff.format]
preview = true
quote-style = "double"
indent-style = "space"
line-ending = "lf"

[tool.pytest.ini_options]
asyncio_mode = "auto"

[tool.uv.workspace]
members = ["app/chatbot/test/firecrawl"]
