name: Check python imports

on:
  push:
    branches:
      - main
      - dev
    paths:
      - "api/**"
  pull_request:
    branches:
      - main
      - dev
    paths:
      - "api/**"
  workflow_dispatch:

jobs:
  check_python_imports:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: "${{ github.workspace }}/api"
    defaults:
      run:
        working-directory: ./api
    strategy:
      matrix:
        python-version: ["3.12", "3.13"]
    steps:
      - name: Clone the repository
        uses: actions/checkout@v4
      - name: Install the latest version of uv and set the python version
        uses: astral-sh/setup-uv@v6
        with:
          version: ">=0.7.0"
          python-version: ${{ matrix.python-version }}
          enable-cache: true
      - name: Generate random password
        run: |
          echo "POSTGRES_PASSWORD=$(openssl rand -base64 16)" >> $GITHUB_ENV
          echo "FIRST_USER_PASSWORD=$(openssl rand -base64 16)" >> $GITHUB_ENV
      - name: Check python imports
        run: |
          uv run python ../.github/workflows/check_python_imports.py --src_path app tests